highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
#paginate: 5
port: 4000
safe: true
url: http://nicktunac.github.io/resume
author: Dominick Tunac

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Nick Tunac's Resume
name: Dominick Tunac
email: dominick.tunac@gmail.com
email_full: mailto:dominick.tunac@gmail.com
website: nicktunac.github.io
github: nicktunac
twitter: nicknyak
tel: +63 935 4551716
tel_full: tel:+447450223192
google_maps: 'https://www.google.co.uk/maps/place/14+Gowrie+St,+Dundee,+Dundee+City+DD2+1ES'
address: 14 Gowrie Street
postcode: DD2 1ES
city: Dundee
country: United Kingdom
google_analytics: UA-69291029-1

